version: '3.8'

services:
  bot-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: discord-bot-prod
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./.env.production:/app/.env
    command: npm start 