FROM node:20-alpine

WORKDIR /app

# Copier tout le code source
COPY . .

# Installer nodemon et ts-node globalement
RUN npm install -g nodemon ts-node typescript

# Installer les dépendances du projet
RUN npm install

# Le code source sera monté en volume
CMD ["nodemon", "--watch", "src", "--ext", "ts,json", "--exec", "ts-node", "src/index.ts"] 