version: '3.8'

services:
  bot-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: discord-bot-dev
    restart: unless-stopped
    env_file:
      - env.development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    command: nodemon --watch src --ext ts,json --exec ts-node src/index.ts
    # Configuration pour le hot reload
    stdin_open: true
    tty: true
    networks:
      - default
      - bots-discord-api_app-network

networks:
  bots-discord-api_app-network:
    external: true 